---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secretstore-database
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: "vault-approle-database"
            key: "role-id"
          secretRef:
            name: "vault-approle-database"
            key: "secret-id"
