apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
  - secretKey: url
    remoteRef:
      key: bankapp/dev/database
      property: url
  - secretKey: username
    remoteRef:
      key: bankapp/dev/database
      property: username
  - secretKey: password
    remoteRef:
      key: bankapp/dev/database
      property: password
