apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- vault-approle-dev-secret.yaml
- vault-approle-prod-secret.yaml
- dev-secretstore.yaml
- prod-secretstore.yaml
- dev-app-external-secret.yaml
- prod-app-external-secret.yaml

commonLabels:
  app: bankapp
  component: external-secrets
