apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev-secretstore.yaml
- prod-secretstore.yaml
- database-secretstore.yaml
- dev-app-external-secret.yaml
- prod-app-external-secret.yaml
- dev-mysql-external-secret.yaml
- prod-mysql-external-secret.yaml

commonLabels:
  app: app-javdes
  component: external-secrets
