apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-root-secret
  namespace: database
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore-database
    kind: SecretStore
  target:
    name: mysql-root-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: mysql/prod/root
      property: password
