apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secretstore
  namespace: prod
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle" 
          roleRef:
            name: "vault-approle-prod"
            key: "role-id"
          secretRef:
            name: "vault-approle-prod"
            key: "secret-id"
