apiVersion: v1
kind: Secret
metadata:
  name: vault-approle-prod
  namespace: prod
type: Opaque
data:
  role-id: YTVlZjFmZjEtNGRhNi1iMzkyLTQ3NjctOTM0ZDRmMmJjYjc1  # Prod role-id
  secret-id: MDI3ZWVjMDYtY2U0Yi0zYmQ2LWQ0ZmUtZDg1YWQ3OTAwNmZj  # Prod secret-id
