apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-javdes
  labels:
    app: app-javdes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-javdes
  template:
    metadata:
      labels:
        app: app-javdes
    spec:
      containers:
      - name: app-javdes
        image: 34.147.56.126:30083/javdes/app-javdes:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        # SPRING_PROFILES_ACTIVE will be set in overlays
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
