apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-javdes-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app-javdes.local
    secretName: app-javdes-tls
  rules:
  - host: app-javdes.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-javdes-service
            port:
              number: 80
