apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-javdes
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: app-javdes
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
