apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

patches:
- target:
    kind: Ingress
    name: bankapp-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: bankapp-prod.local
    - op: replace
      path: /spec/tls/0/hosts/0
      value: bankapp-prod.local
    - op: replace
      path: /spec/tls/0/secretName
      value: bankapp-prod-tls
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: selfsigned-ca-issuer

commonLabels:
  env: prod
