apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base
- ../../../vault-secrets/prod-secretstore.yaml
- ../../../vault-secrets/prod-app-external-secret.yaml

patchesStrategicMerge:
- deployment-patch.yaml

patches:
- target:
    kind: Ingress
    name: app-javdes-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: app-javdes-prod.local
    - op: replace
      path: /spec/tls/0/hosts/0
      value: app-javdes-prod.local

commonLabels:
  env: prod
