apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-javdes
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app-javdes
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
