apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

patches:
- target:
    kind: Ingress
    name: bankapp-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: bankapp-dev.local
    - op: replace
      path: /spec/tls/0/hosts/0
      value: bankapp-dev.local

commonLabels:
  env: dev
