apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/selfsigned-cluster-issuer.yaml
  - certificates/bankapp-certificates.yaml
  - ingress-nginx/

namespace: cert-manager
